name: Publish

on:
  release:
    types: [ published ]
    
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}    
    - name: Install dependencies
      run: dotnet restore
    - name: Pack Cudio
      run: dotnet pack Source/Cudio -c Release -o Publish --no-restore
    - name: Pack Cudio.AspNetCore
      run: dotnet pack Source/Cudio.AspNetCore -c Release -o Publish --no-restore
    - name: Publish NuGet to nuget.org
      run: dotnet nuget push Publish/*.nupkg --skip-duplicate -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      
